version: '3.8'

services:
  # Servicio de la base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: examen_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: examen
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - examen_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Servicio de la aplicación .NET Core Web API
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: examen_webapi_dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__WebinarDB=Server=mysql;user=root;password=root1234;database=examen
    ports:
      - "5244:5000"
    volumes:
      # Montamos el código fuente para hot reload
      - .:/app
      - /app/bin
      - /app/obj
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - examen_network
    restart: unless-stopped

  # Servicio opcional para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: examen_phpmyadmin_dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root1234
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - examen_network

volumes:
  mysql_data:
    driver: local

networks:
  examen_network:
    driver: bridge